# Generated by Django 5.2.6 on 2025-10-14 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_data_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='user',
        ),
    ]
