# Generated by Django 5.2.6 on 2025-09-25 12:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_remove_data_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='date',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
