# Generated by Django 5.2.6 on 2025-09-28 09:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_data_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
